Repository encore-full-stack-5/DH_lottery, pull requests merged in 2024-06, with the labels that each got.

#2 [Feat]:global header bar 추가
  package-lock.json
  package.json
  public/logo.png
  public/vite.svg
  public/won-icon.svg
  src/App.jsx
  src/components/header/HeaderBar.css
  src/components/header/HeaderBar.jsx
  src/css/Payment.css
  src/main.jsx
  src/pages/Layout.jsx
  src/pages/Payment.jsx
Labels: feature

#3 [Feat] : NavBar 추가
  src/components/header/HeaderBar.css
  src/components/nav/NavBar.css
  src/components/nav/NavBar.jsx
  src/pages/Layout.jsx
Labels: feature

#6 [Refactor]: Refactored li tag to Link tag
  src/components/nav/NavBar.css
  src/components/nav/NavBar.jsx
Labels: refactor

#8 [Feat]: 마이페이지의 사이드바 추가
  src/components/sidebar/MyPageSideBar.css
  src/components/sidebar/MyPageSideBar.jsx
  src/main.jsx
  src/pages/Layout.jsx
  src/pages/Payment.jsx
Labels: feature

#10 Feature/payment
  public/process.png
  src/components/sidebar/MyPageSideBar.css
  src/components/sidebar/MyPageSideBar.jsx
  src/css/Payment.css
  src/main.jsx
  src/pages/Layout.jsx
  src/pages/Payment.jsx
  src/pages/payment/Payment.css
  src/pages/payment/Payment.jsx
  src/pages/withdraw/Withdraw.css
  src/pages/withdraw/Withdraw.jsx
Labels: feature

#23 출금 페이지 퍼블리싱 추가
  package-lock.json
  package.json
  public/calendar.png
  public/withdraw_process.png
  src/App.css
  src/components/payment/nigger.jsx
  src/index.css
  src/pages/withdraw/Withdraw.css
  src/pages/withdraw/Withdraw.jsx
Labels: feature

#25 [Feat]: 예치금 충전 내역 페이지 추가
  src/components/lotto-result/LottoResult.css
  src/components/nav/NavBar.jsx
  src/components/sidebar/MyPageSideBar.jsx
  src/css/Payment.css
  src/main.jsx
  src/pages/payment/Payment.css
  src/pages/payment/Payment.jsx
  src/pages/transaction/Transaction.css
  src/pages/transaction/Transaction.jsx
  src/pages/withdraw/Withdraw.css
Labels: feature

#27 [Fix]: 조회기간 css 중복문제 해결
  src/pages/withdraw/Withdraw.css
  src/pages/withdraw/Withdraw.jsx
Labels: bug

#46 Feature/buying720
  src/pages/p_buying/P_Buying.css
  src/pages/p_buying/P_Buying.jsx
Labels: feature

#55 [feat]: 토스 결제 페이지 추가 및 .env파일로 환경분리 (#54)
  .gitignore
  package-lock.json
  package.json
  src/main.jsx
  src/pages/payment/Checkout.jsx
  src/pages/payment/Fail.jsx
  src/pages/payment/Payment.css
  src/pages/payment/Payment.jsx
  src/pages/payment/Success.jsx
Labels: feature

#57 [fix]: payment css 충돌 해결
  src/pages/payment/Payment.css
  src/pages/payment/Payment.jsx
Labels: bug

#61 [feat]: 예치금 충전 내역 날짜 조회로 가져오는 기능 추가 (#60)
  src/pages/payment/Checkout.jsx
  src/pages/payment/Payment.jsx
  src/pages/payment/Success.jsx
  src/pages/transaction/Transaction.css
  src/pages/transaction/Transaction.jsx
Labels: feature

#64 [feat]: 출금 및 출금 내역 출력 추가 (#62)
  src/pages/payment/Payment.jsx
  src/pages/withdraw/Withdraw.jsx
Labels: feature

#66 [feat]: 충전 성공 페이지 css추가
  src/pages/payment/Success.css
  src/pages/payment/Success.jsx
  src/pages/transaction/Transaction.jsx
  src/pages/withdraw/Withdraw.css
  src/pages/withdraw/Withdraw.jsx
Labels: feature

#67 [feature]: Transaction 리팩터링
  src/pages/transaction/Transaction.jsx
Labels: refactor

#69 FEAT TABLE
  src/css/P_WinningResult.css
  src/pages/P_WinningResult.jsx
Labels: feature

#84 [feat]: userId를 token으로 전환
  src/pages/payment/Success.jsx
  src/pages/transaction/Transaction.jsx
  src/pages/withdraw/Withdraw.jsx
Labels: feature

#89 [fix]: 엔드포인트 수정
  src/pages/payment/Success.jsx
  src/pages/transaction/Transaction.jsx
  src/pages/withdraw/Withdraw.jsx
Labels: refactor
